version: "3.9"

services:
  redis:
    image: redis:7
    container_name: sc_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile.boot
    container_name: sc_server
    volumes:
      - .:/app
      - sqlite_data:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      GEMINI_API_KEY: xxx
      OPENROUTER_API_KEY: xxx
      OPENROUTER_MODEL: openrouter/free
    stdin_open: true
    tty: true

volumes:
  sqlite_data:
